AGstudios/Models/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AGstudios.Models
{
    [Table("Person")]
    public class Person
    {
        public int PersonID { get; set; }

        [DisplayName("Name")]
        public string FirstName { get; set; }

        public string Surname { get; set; }

        [DisplayName("User")]
        public string User { get; set; }

        public string Email { get; set; }

        [DisplayName("Phone")]
        public int PhoneNumber { get; set; }

        [DisplayName("Name|No.")]
        public string HouseNameNumber { get; set; }

        [DisplayName("Street")]
        public string StreetName { get; set; }

        public string Town { get; set; }

        public string County { get; set; }

        [DisplayName("Post Code")]
        public string PostCode { get; set; }

        public bool Confirmed { get; set; }
    }
}

AGstudios/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AGstudios.Models;

namespace AGstudios.Controllers
{
    public class PeopleController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: People
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(db.People.ToList());
        }

        // GET: People/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // GET: People/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: People/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "PersonID,FirstName,Surname,User,Email,PhoneNumber,HouseNameNumber,StreetName,Town,County,PostCode")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.People.Add(person);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(person);
        }

        // GET: People/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "PersonID,FirstName,Surname,User,Email,PhoneNumber,HouseNameNumber,StreetName,Town,County,PostCode")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.Entry(person).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(person);
        }

        // GET: People/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Person person = db.People.Find(id);
            db.People.Remove(person);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AGstudios/Views/People/Create.cshtml
@model AGstudios.Models.Person

@{
    ViewBag.Title = "Create";
}

<div class="d-row voffset4">
    <div class="d-column">
        <div class="container">
            <h2>Create New</h2>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Family & Friends</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.User, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.User, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.User, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.HouseNameNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.HouseNameNumber, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.HouseNameNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.StreetName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.StreetName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.StreetName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Town, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Town, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Town, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.County, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.County, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.County, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PostCode, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PostCode, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PostCode, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-primary" />
                            <a class="btn btn-default" href="@Url.Action("Index", "People")">Cancel</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AGstudios/Views/People/Delete.cshtml
@model AGstudios.Models.Person

@{
    ViewBag.Title = "Delete";
}

<div class="d-row voffset4">
    <div class="d-column">
        <div class="container">
            <h2>Delete</h2>

            <div class="d-row">
                <div class="col-sm-5">
                    <h3 class=" alert alert-danger">Are you sure you want to delete this?</h3>
                </div>
            </div>
            <div>
                <h4>Friends & Family</h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.FirstName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.FirstName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Surname)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Surname)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.User)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.User)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Email)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Email)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PhoneNumber)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.PhoneNumber)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.HouseNameNumber)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.HouseNameNumber)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.StreetName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.StreetName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Town)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Town)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.County)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.County)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PostCode)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.PostCode)
                    </dd>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-danger" />
                        <a class="btn btn-default" href="@Url.Action("Index", "People")">Cancel</a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

AGstudios/Views/People/Details.cshtml
@model AGstudios.Models.Person

@{
    ViewBag.Title = "Details";
}

<div class="d-row voffset4">
    <div class="d-column">
        <div class="container">
            <h2>Details</h2>

            <div>
                <h4>Of Friends & Family</h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.FirstName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.FirstName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Surname)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Surname)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.User)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.User)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Email)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Email)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PhoneNumber)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.PhoneNumber)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.HouseNameNumber)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.HouseNameNumber)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.StreetName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.StreetName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Town)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Town)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.County)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.County)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PostCode)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.PostCode)
                    </dd>

                </dl>
            </div>
            <a class="btn btn-primary" href="@Url.Action("Edit", "People", new { id = Model.PersonID })">Edit</a>
            <a class="btn btn-default" href="@Url.Action("Index", "People")">Cancel</a>
        </div>
    </div>
</div>

AGstudios/Views/People/Edit.cshtml
@model AGstudios.Models.Person

@{
    ViewBag.Title = "Edit";
}

<div class="d-row voffset4">
    <div class="d-column">
        <div class="container">
            <h2>Edit</h2>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Friends & Family</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.PersonID)

                    <div class="form-group">
                        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.User, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.User, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.User, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.HouseNameNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.HouseNameNumber, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.HouseNameNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.StreetName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.StreetName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.StreetName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Town, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Town, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Town, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.County, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.County, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.County, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PostCode, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PostCode, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PostCode, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-primary" />
                            <a class="btn btn-default" href="@Url.Action("Index", "People")">Cancel</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AGstudios/Views/People/Index.cshtml
@model IEnumerable<AGstudios.Models.Person>

@{
    ViewBag.Title = "Index";
}

<div class="d-row voffset4">
    <div class="d-column">
        <div class="container">
            <div>
                <h2>Friends & Family</h2>
                <a class="btn btn-primary" href="@Url.Action("Create", "People")">Create New</a>
                @Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink", @class = "btn btn-primary" })
            </div>
            <div class="table table-responsive voffset2">
                <table class="table table-condensed details-table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.FirstName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Surname)
                            </th>
                            <th>
                                @Html.DisplayNameFor(Model => Model.User)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Email)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Confirmed)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.PhoneNumber)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.HouseNameNumber)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.StreetName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Town)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.County)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.PostCode)
                            </th>
                            <th></th>
                        </tr>
                    </thead>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.FirstName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Surname)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.User)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>
                            <td class="tick">
                                @if (item.Confirmed == true)
                                {
                                    <i class="glyphicon glyphicon-ok"></i>
                                }
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PhoneNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.HouseNameNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.StreetName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Town)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.County)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PostCode)
                            </td>
                            <td>
                                <a class="btn btn-primary btn-xs" href="@Url.Action("Edit", "People", new { id = item.PersonID })"><i class="glyphicon glyphicon-edit"></i></a>
                                <a class="btn btn-info btn-xs" href="@Url.Action("Details", "People", new { id = item.PersonID })"><i class="glyphicon glyphicon-th-list"></i></a>
                                <a class="btn btn-danger btn-xs" href="@Url.Action("Delete", "People", new { id = item.PersonID })"><i class="glyphicon glyphicon-remove"></i></a>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</div>