AGstudios/Controllers/RoleController.cs
using AGstudios.Models;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AGstudios.Controllers
{
    public class RoleController : Controller
    {
        private ApplicationRoleManager _roleManager;

        public RoleController()
        {
        }

        public RoleController(ApplicationRoleManager roleManager)
        {
            RoleManager = roleManager;
        }

        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        [Authorize(Roles = "Admin")]
        // GET: Role
        public ActionResult Index()
        {
            List<RoleViewModel> list = new List<RoleViewModel>();
            foreach (var role in RoleManager.Roles)
                list.Add(new RoleViewModel(role));
            return View(list);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Create(RoleViewModel model)
        {
            var role = new ApplicationRole() { Name = model.Name };
            await RoleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            return View(new RoleViewModel(role));
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(RoleViewModel model)
        {
            var role = new ApplicationRole() { Id = model.Id, Name = model.Name };
            await RoleManager.UpdateAsync(role);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Details(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            return View(new RoleViewModel(role));
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            return View(new RoleViewModel(role));
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            await RoleManager.DeleteAsync(role);
            return RedirectToAction("Index");
        }
    }
}

AGstudios/Controllers/RsvpController.cs
using AGstudios.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AGstudios.Controllers
{
    public class RsvpController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Rsvp
        [Authorize(Roles = "User, Admin")]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetPeople()
        {
            
            return Json(db.People.ToList(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public void Confirmed(Person person)
        {
            var model = db.People.FirstOrDefault(x => x.PersonID == person.PersonID);
            if (model != null)
            {
                model.PersonID = person.PersonID;
                model.Confirmed = person.Confirmed;
                db.SaveChanges();
            }else
            {
                ViewBag.ErrorMessage = "Error, you have not confirmed!";
            }
        }
        
        [HttpPost]
        public void Reset(List<Person> person)
        {
            if (person != null)
            {
                foreach (var p in person)
                {
                    var reset = db.People.FirstOrDefault(x => x.Confirmed == true && x.PersonID == p.PersonID);
                    if (p.Confirmed == true)
                    {
                        reset.Confirmed = false;
                    }
                }
                db.SaveChanges();
            }
            else
            {
                ViewBag.ErrorMessage = "Error, Invitees not deselected!";
            }
        }
    }
}

AGstudios/Views/Shared/_BridgeAccordian.cshtml
<div class="bs-example">
    <div class="panel-group" id="accordion2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <a data-toggle="collapse" data-parent="#accordion2" href="#collapse1">
                    <h4 class="panel-title">Bridge Log-in</h4>
                </a>
            </div>
            <div id="collapse1" class="panel-collapse collapse in">
                <div class="">
                    <img src="~/Images/login.jpg" alt="bridge log in screen shot" />
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <a data-toggle="collapse" data-parent="#accordion2" href="#collapse4">
                    <h4 class="panel-title">Bridge Home Page</h4>
                </a>
            </div>
            <div id="collapse4" class="panel-collapse collapse">
                <div class="">
                    <img src="~/Images/Bridge.jpg" alt="bridge home screen shot" />
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <a data-toggle="collapse" data-parent="#accordion2" href="#collapse2">
                    <h4 class="panel-title">Patient Overview</h4>
                </a>
            </div>
            <div id="collapse2" class="panel-collapse collapse">
                <div class="">
                    <img src="~/Images/PatientOverview.jpg" alt="patient overview screen shot" />
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <a data-toggle="collapse" data-parent="#accordion2" href="#collapse3">
                    <h4 class="panel-title">Patient Details</h4>
                </a>
            </div>
            <div id="collapse3" class="panel-collapse collapse">
                <div class="">
                    <img src="~/Images/PatientDetails.jpg" alt="Patient details screen shot" />
                </div>
            </div>
        </div>
    </div>
</div>                              		                            

AGstudios/Views/Shared/_Footer.cshtml
<div class="bg-black footer">
    <div class="container">
        <p>&copy; AG-Studios @DateTime.Now.Year</p>
    </div>
</div>

AGstudios/Views/Shared/_GraphicIcon.cshtml
<svg version="1.1" id="lamp" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     viewBox="0 0 1009.9766 1009.9527" enable-background="new 0 0 1009.9766 1009.9527" xml:space="preserve">

<g id="lamp-lamp">
<path fill="#FFFFFF" d="M508.7783,559.1792c6.2569,4.2305,14.7188,2.6221,18.961-3.623l183.5732-270.294
		c4.2305-6.2446,2.6211-14.7304-3.6113-18.955c-6.2451-4.2432-14.7305-2.628-18.9619,3.6113L505.167,540.2056
		C500.9004,546.4507,502.5449,554.9361,508.7783,559.1792z" />



<path fill="#FFFFFF" d="M417.9155,351.7115l9.2007,6.2446c-17.3047,66.2339,6.8409,138.9038,65.6201,180.5571l189.8536-279.5
		c-60.3887-39.2934-136.8301-34.9551-192.0459,5.5479l-9.1773-6.2452c-25.7905-17.5073-60.9009-10.8095-78.4082,14.9932
		C385.4151,299.0757,392.125,334.1919,417.9155,351.7115z" />



<path fill="#FFFFFF" d="M592.502,475.646c26.076,8.1582,55.4541-1.1977,71.6035-24.9619
		c16.1484-23.7822,14.0029-54.543-3.1943-75.7685L592.502,475.646z" />



<path fill="#FFFFFF" d="M491.8784,700.6929c-19.188,0-37.6489,3.123-54.9057,8.8311l-108.6563-90.4454
		c3.0747-6.3643,4.9219-13.4433,5.1245-20.9755c0.4292-15.5645-6.1255-29.6875-16.8042-39.4366l90.4454-150.4345
		c-0.6319-14.4922,0.3457-29.1573,3.2539-43.6914l-0.7627-0.5181c-6.6744-4.523-12.3477-10.0767-17.0313-16.3277L245.5459,560.2515
		c-9.0215,8.9863-14.7544,21.3096-15.124,35.0391c-0.4649,17.0185,8.0332,31.582,19.8555,42.0937
		c0,0,94.9502,87.9072,120.8242,111.8623c-9.1651,8.748-17.4478,18.4258-24.5508,28.9492h290.6797
		C605.7305,731.4888,552.4815,700.6929,491.8784,700.6929z M281.0972,627.564c-17.0542-0.4766-30.4981-14.6582-30.0332-31.7012
		c0.4771-17.043,14.6592-30.4863,31.7134-30.0215c17.0312,0.4766,30.4746,14.6592,30.0214,31.7012
		C312.3106,614.5972,298.1397,628.0288,281.0972,627.564z" />



<path fill="#FFFFFF" d="M762.7852,371.7036l-26.1953,4.7911c-7.7227,1.4301-12.8233,8.8369-11.3936,16.5839
		c1.4063,7.7286,8.8311,12.8355,16.542,11.417l26.1836-4.8266c7.7236-1.4004,12.8242-8.8252,11.4297-16.5542
		C777.9219,375.3623,770.4961,370.2857,762.7852,371.7036z" />



<path fill="#FFFFFF" d="M725.459,477.8867c-6.4482-4.4516-15.3271-2.8481-19.7598,3.6412
		c-4.458,6.4589-2.8369,15.3203,3.6231,19.7773l21.9286,15.0947c6.4355,4.4864,15.3144,2.8535,19.7715-3.623
		c4.4697-6.4541,2.8369-15.3272-3.6348-19.7725L725.459,477.8867z" />



<path fill="#FFFFFF" d="M627.0283,533.937c-7.747,1.3828-12.8477,8.795-11.4414,16.542l4.8155,26.1719
		c1.4297,7.7471,8.8427,12.8477,16.5771,11.417c7.7227-1.4063,12.8359-8.8428,11.417-16.5654l-4.8144-26.1485
		C642.1641,537.6079,634.751,532.5064,627.0283,533.937z" />



</g>
</svg>

AGstudios/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AGstudios</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="header">
        <div class="navbar navbar-inverse">
            <div class="navbar-header">
                <h1 class="pull-left">AG-Studios</h1>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbarCollapse" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("AGstudios",  "Index", "Home", null, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("Portfolio", "Portfolio", "Home")</li>
                    <li>@Html.ActionLink("WebDesign", "WebDesign", "Home")</li>
                    <li>@Html.ActionLink("GraphicDesign", "GraphicDesign", "Home")</li>

                    @if (User.IsInRole("User") || User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("RSVP", "Index", "Rsvp")</li>
                    }
                    
                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Roles", "Index", "Role")</li>
                        <li>@Html.ActionLink("People", "Index", "People")</li>
                    }
                    
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="d-page">
        @RenderBody()
    </div>
    @Html.Partial("_Footer")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    @RenderSection("scripts", required: false)
</body>
</html>

AGstudios/Views/Shared/_MyStaffFileAccordian.cshtml
<div class="bs-example">
    <div class="panel-group" id="accordion">
        <div class="panel panel-default">
            <div class="panel-heading">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                    <h4 class="panel-title">My Staff</h4>
                </a>
            </div>
            <div id="collapseOne" class="panel-collapse collapse in">
                <div class="">
                    <img src="~/Images/Home.jpg" alt="my staff file home page" />
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                    <h4 class="panel-title">Admin</h4>
                </a>
            </div>
            <div id="collapseTwo" class="panel-collapse collapse">
                <div class="">
                    <img src="~/Images/Admin.jpg" alt="my staff file admin page" />
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                    <h4 class="panel-title">Hr Dashboard</h4>
                </a>
            </div>
            <div id="collapseThree" class="panel-collapse collapse">
                <div class="">
                    <img src="~/Images/HrDashboard.jpg" alt="my staff file Hr page" />
                </div>
            </div>
        </div>
    </div>
</div>                              		                            

AGstudios/Views/Shared/_PortfolioIcon.cshtml
<svg version="1.1" id="portfolio-suitcase" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px"
     y="0px" viewBox="0 0 1009.9766 1009.9287" enable-background="new 0 0 1009.9766 1009.9287" xml:space="preserve">

<g id="portfolio-suitcase-portfolio-suitcase">
<path fill="#fff" d="M525.3438,519.2412v-28.9126c0-11.2387-9.1172-20.3559-20.3555-20.3559
		c-11.251,0-20.3682,9.1172-20.3682,20.3559v28.9126c0,11.2393,9.1172,20.3682,20.3682,20.3682
		C516.2266,539.6094,525.3438,530.4805,525.3438,519.2412z" />



<path fill="#fff" d="M538.4776,513.9854h0.0117c-0.0117,18.5215-4.9219,38.7578-33.501,38.7578
		c-29.2227,0-33.5015-20.2607-33.5015-38.7578v-3.2891H230.3985V684.127c0,43.3574,35.4677,78.8252,78.8252,78.8252h391.5292
		c43.3458,0,78.8252-35.4678,78.8252-78.8252V510.6963H538.4776V513.9854z" />



<path fill="#fff" d="M700.7529,342.522H309.2237c-43.3575,0-78.8252,35.48-78.8252,78.8374v73.5693h241.1123
		c0.3691-18.1865,4.8984-38.1015,33.4775-38.1015c28.5791,0,33.0957,19.915,33.4658,38.1015h241.124v-73.5693
		C779.5781,378.002,744.0987,342.522,700.7529,342.522z" />



<path fill="#fff" d="M389.4673,330.9258l22.0244,5.8164c6.0781,1.5967,12.3111-2.0381,13.9082-8.1162
		c0.2388-0.8818,0.3335-1.7642,0.3579-2.6338c12.1919-31.9643,42.9756-54.7041,79.2305-54.7637
		c36.2539,0.0596,67.0391,22.7994,79.2305,54.7637c0.0234,0.8696,0.1191,1.752,0.3574,2.6338
		c1.5976,6.0781,7.8301,9.7129,13.8965,8.1162l22.0244-5.8164c6.0781-1.5849,9.7129-7.8301,8.1162-13.9082
		c-1.6094-6.0781-7.8301-9.7129-13.9199-8.1162l-10.0469,2.6582c-17.0781-38.0664-55.2402-64.584-99.6582-64.5957
		c-44.4185,0.0117-82.5918,26.5293-99.6699,64.5957l-10.0352-2.6582c-6.0898-1.5967-12.3115,2.0381-13.9199,8.1162
		C379.7661,323.0957,383.3892,329.3409,389.4673,330.9258z" />

    </g>
</svg>

AGstudios/Views/Shared/_WebIcon.cshtml
<svg version="1.1" id="screen" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     viewBox="0 0 1009.9766 1009.9527" enable-background="new 0 0 1009.9766 1009.9527" xml:space="preserve">
<g id="screen-label">
	
</g>
<path id="screen-screen" fill="#FFFFFF" d="M711.9551,238.7705H298.0449c-37.3393,0.0777-67.5634,30.3013-67.6464,67.6402v294.7197
	c0.083,37.3389,30.3071,67.5752,67.6464,67.6465h147.9493v41.1172l-75.9888,36.8027h-30.856
	c-7.5078,0-13.5859,5.458-13.5859,12.2275c0,6.7696,6.0781,12.251,13.5859,12.251h331.6895c7.5078,0,13.5986-5.4814,13.5986-12.251
	c0-6.7695-6.0908-12.2275-13.5986-12.2275h-30.8438l-75.9892-36.8027v-41.1172h147.9492
	c37.3281-0.0713,67.5752-30.3076,67.623-67.6465V306.4107C779.5303,269.0718,749.2832,238.8482,711.9551,238.7705z
	 M672.7578,646.5015h-54.4179c-4.6602,0-8.4258-3.7774-8.4258-8.4258c0-4.6475,3.7656-8.4141,8.4258-8.4141h54.4179
	c4.6592,0,8.4258,3.7666,8.4258,8.4141C681.1836,642.7241,677.417,646.5015,672.7578,646.5015z M699.6084,646.4429
	c-4.6123,0-8.3428-3.7422-8.3428-8.3672c0-4.5996,3.7305-8.3418,8.3428-8.3418c4.6006,0,8.3428,3.7422,8.3428,8.3418
	C707.9512,642.7007,704.209,646.4429,699.6084,646.4429z M740.9522,576.9722c-0.0479,15.8271-13.1817,28.9609-28.9971,28.9971
	H298.0449c-15.8154-0.0362-28.9609-13.17-28.9848-28.9971V306.4107c0.0239-15.8208,13.1694-28.9483,28.9848-29.002h413.9102
	c15.8154,0.0537,28.9492,13.1812,28.9971,29.002V576.9722z M617.8516,348.7495H396.0225v-21.3691h221.8291V348.7495z
	 M312.8233,374.7007v18.7173h388.2158v-18.7173H312.8233z M312.8233,533.5552h114.1855V419.3755H312.8233V533.5552z
	 M449.8321,533.5552h114.1972V419.3755H449.8321V533.5552z M586.8643,533.5552h114.1747V419.3755H586.8643V533.5552z" />



</svg>